# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build 
   jobs:
   - job: FisrtJob
     steps:
     - bash: echo build FirstJob 
     - bash: echo $(PipelineLevelVariable)
   - job: SecondJob
     steps:
     - bash: echo build SecondJob   
 - stage: DevDeploy
   variables: 
     environment:  Dev
   dependsOn: Build
   jobs:
   - job: DevDeployJob
     steps:
     - bash: echo build $(environment)DeployJob
 - stage: QADeploy
   variables:
     environment: QA
   dependsOn: DevDeploy
   jobs:
   - job: QADeployJob
     steps:
     - bash: echo build $(environment)DeployJOb 
 - stage: ProdDeploy
   variables:
     environment: Prod
   dependsOn: 
   - DevDeploy
   - QADeploy
   jobs:
   - job: ProdDeployJob
     steps:
     - bash: echo build $(environment)DeployJOb 


